### ISSUE TITLE
unclear how to use

### ISSUE THREAD

**Issue by GeorgeWL** [Lexedia/VixBluesky#1]
https://github.com/Rapougnac/VixBluesky?tab=readme-ov-file#simply-append-x-at-the-end-of-bskyapp

so the fixer url is bskyx.app ?

**Comment by Lexedia** [comment]
Yes, I didn't have the time to add a proper description, my bad.

EDIT: I swear I added the URL in the description, but I think it didn't work? Anyway, I added the link in the GitHub description now, I'll edit the README tomorrow, I'm on vacation right now.

**Comment by Lexedia** [comment]
Hi, I've updated the README, hope it's clearer now :3
Feel free to reopen this issue if you think something's still missing.
