### ISSUE TITLE
Seems to be broken?

### ISSUE THREAD

**Issue by Invertex** [Lexedia/VixBluesky#10]
Doesn't seem to be able to handle embedding at all anymore. Perhaps an issue with login? As I see this message when I visit the url:

```
Failed to login to Bluesky! 

 SyntaxError: "undefined" is not valid JSON 

 Error: Failed to login to Bluesky!
    at index.js:48406:17
    at async dispatch (index.js:46487:17)
    at async index.js:46711:25
```

**Comment by Lexedia** [comment]
See https://github.com/Rapougnac/VixBluesky/issues/4#issuecomment-2357207227
I'll try to push a fix this evening, I restarted the service so this shouldn't occurs for the next 12-24hrs, this should be enough for me to fix this

**Comment by Invertex** [comment]
Ahh missed that, thanks!

**Comment by Lexedia** [comment]
I'll keep this open just to keep track of it, hope you don't mind.
