### ISSUE TITLE
Video Embeds Are Not Working

### ISSUE THREAD

**Issue by mobiusscarf** [Lexedia/VixBluesky#14]
As of this posting, new video embeds (even ones under 30 seconds) are not posting. Everything but the video loads in.

Here are some examples: 
https://bskyx.app/profile/foldablehuman.bsky.social/post/3l4yi2o2pjp2o
https://bskyx.app/profile/kekeflipnote.bsky.social/post/3l4were2ozi2c
![image](https://github.com/user-attachments/assets/a655c141-dd8a-4f6b-ae42-35ff9f348a15)

**Comment by Lexedia** [comment]
I'm aware, that's why #12 hasn't still been merged, all the changes I did work perfectly locally, but once deployed it doesn't.

**Comment by Lexedia** [comment]
Okay, silly me, turns out i completely forgot that i set silent logs for ffmpeg, which had an error...
This is pretty easy to fix tho, i should be able to release a fix this afternoon

**Comment by Lexedia** [comment]
Hi, this is now fixed, thank you for reporting this!
