### ISSUE TITLE
Text-only posts not rendering?

### ISSUE THREAD

**Issue by tuzonghua** [Lexedia/VixBluesky#16]
It looks like text-only posts aren't rendering. The example below shows a video post, two text-only posts, then an image post.
![image](https://github.com/user-attachments/assets/bb573eef-7b9b-49d2-b6a7-68036858cb08)

**Comment by Juniteevee** [comment]
I dont think i realized this was an issue here too, I thought it was something i messed up on my switch to using nodejs instead of cloudfare cause i dont like serverless design. Between this and the spoiler issue I should probably make an actual fork and and PR these changes towards the main repo

**Comment by Juniteevee** [comment]
uploaded my fork and made a pr to fix this.
https://github.com/Rapougnac/VixBluesky/pull/19
