### ISSUE TITLE
Improper spoiler embed

### ISSUE THREAD

**Issue by imrobbybobby** [Lexedia/VixBluesky#17]
Does not seem to embed when the link is within a spoiler, due to the 2 || at the end or whatever follows.
![Screenshot_20241017-165911.png](https://github.com/user-attachments/assets/0161d230-fdc8-42fa-a0d6-5abe3d5a8d24)

![Screenshot_20241017-165951.png](https://github.com/user-attachments/assets/5765cac6-1615-401f-8c2d-fbbe56840aa5)

**Comment by Juniteevee** [comment]
Yea i noticed this too. turns out discord sends || on the end when the spoiler is against it. Very silly. | isnt a valid character in post or user params so you can just replaceAll('|',''). Thats how i handled it on my fork

**Comment by Juniteevee** [comment]
uploaded my fork and made a pr to fix this.
https://github.com/Rapougnac/VixBluesky/pull/20
