### ISSUE TITLE
Request: Discord Bot

### ISSUE THREAD

**Issue by cjshrader** [Lexedia/VixBluesky#2]
First off thank you for resurrecting this.

Honestly this may be way more than you want to take on, but I figure it doesn't hurt to ask. FixTweet has a companion discord bot (https://github.com/Kyrela/FixTweetBot) that automatically removes the embed from a linked Twitter link and then posts the embed of the fxtwitter link. Would there be any appetite for creating a similar bot for VixBluesky?

**Comment by Lexedia** [comment]
Hi,
It's an interesting idea, but this won't be my first priority right now. I'll try to see what I can come up with.
I hope you'll understand :)

**Comment by cjshrader** [comment]
I absolutely understand!

Actually I'm going to close this one, I made the same request to the makers of FixTweetBot and they said that feature should be coming within a month. Seems easier to put the feature there than for you to clone the bot.

Here is that comment: https://github.com/Kyrela/FixTweetBot/issues/5
