### ISSUE TITLE
Avoid rate-limits

### ISSUE THREAD

**Issue by Kyrela** [Lexedia/VixBluesky#4]
Bot is currently rate-limited.

Would be great if VixBluesky could avoid rate-limit with techniques such as the ones used by FxTwitter (for example, [guest token](https://github.com/FixTweet/FxTwitter?tab=readme-ov-file#why-fxtwitter-is-nicer-to-develop-for-and-deploy).

Don't know if they are applicable for Bluesky, but I think this is worth searching and trying, as it'll greatly increase the stability of VixBluesky, while reducing needs and dependancies.

**Comment by Kyrela** [comment]
In the meantime, using the og bluesky (by GETing `https://embed.bsky.app/oembed?url=post_link`) if rate-limited would be a great idea
doc: https://docs.bsky.app/docs/advanced-guides/oembed

I'd probably have opened a pull request if I knew how to code in typescript 😅, sorry

**Comment by Lexedia** [comment]
Hi, sorry for the late response.
I knew this issue was here for a while but, let's admit it that i was a little bit lazy.
Anyways, thanks for (re)bringing me to my attention, I merged a PR and deployed the changes, it should work now (i hope — at least).
Don't hesitate to open a new issue if something's still wrong for you.


> I'd probably have opened a pull request if I knew how to code in typescript 😅, sorry

No worries!

**Comment by Lexedia** [comment]
I will see for the oembed fallback, I currently have some personal issues, so this won't be a first priority, but this is a good idea, thanks for reaching me out!

**Comment by Delphox** [comment]
I think it either got rate limited again or the account associated with the service got suspended. Just going to bskyx.app at all shows an authentication error for the past hours.

**Comment by Lexedia** [comment]
That wasn't a rate-limit issue, nor the account didn't get suspended, just a bug with the persistSession method, i need to investigate this.
