### ISSUE TITLE
Not showing the full video and also no text

### ISSUE THREAD

**Issue by StarCaliburn** [Lexedia/VixBluesky#8]
I'm happy that VixBluesky is showing video now but 2 issues: 
1. Text is not showing
2. It's not playing the full video.

The post in question
<img width="590" alt="Screenshot 2024-09-14 at 6 32 42 PM" src="https://github.com/user-attachments/assets/2c85e9c9-2268-4e59-bcbe-492abd81fb02">

The post with VixBluesky
<img width="406" alt="Screenshot 2024-09-14 at 6 32 17 PM" src="https://github.com/user-attachments/assets/45b5293c-fa2d-4e51-ba6a-c575972a9aac">

I hope this gets fixed soon, thank you for doing so much hard work with this.

**Comment by Lexedia** [comment]
Hi, could you please provide the link of the skeet? Ty very much.

I'm also aware that the text is not displayed, that's because discord doesn't allow putting a description with a video embed. I need to find a workaround, and also see https://github.com/Rapougnac/VixBluesky/issues/6#issuecomment-2351068147

**Comment by StarCaliburn** [comment]
Yeah sure, here's the link to the skeet: https://bsky.app/profile/sonichedgeblog.bsky.social/post/3l45jkpmpsp2c

**Comment by fr0r** [comment]
Noticed the same with https://bskyx.app/profile/williamcastro.bsky.social/post/3l4amiqsdgg2j

It only played/showed seven seconds of the original eighteen the skeet has.

**Comment by Delphox** [comment]
As for a workaround for showing the text, you could use the same workaround that vxtwitter uses where they append the likes/retweet count to provider name instead (you can use \n for line break there also) and use the embed author field for the text.

**Comment by Lexedia** [comment]
Hi, this should be fixed.
Here's a quick preview
![image](https://github.com/user-attachments/assets/53857e81-391f-4ec3-8c32-9172fcc8a95e)

**Comment by StarCaliburn** [comment]
Took a little bit but yeah it's working now. Thank you so much, keep up the good work.

**Comment by Delphox** [comment]
Hey I noticed it's not picking up videos when a skeet has a quote, I assume cuz it's prioritizing the quote rather than the video.

Here's an example: https://bskyx.app/profile/sanzitos.bsky.social/post/3l4biozpkvd27

Otherwise it's working great, thanks for the good work!

**Comment by mobiusscarf** [comment]
While not as bad as before, it still seems to cut out about 10-20% off the end of the video it's embedding. Here's an example of a 30-second video that, when embedded, cuts out about 6 seconds from the end, including the user's Patreon tag at the very end. https://bsky.app/profile/bakertoons.com/post/3l4aabftulc2f

**Comment by Lexedia** [comment]
cc @Delphox, @mobiusscarf 
This has been fixed by #11

**Comment by mobiusscarf** [comment]
@Rapougnac seems to be fixed for other accounts, but for some reason, it no longer embeds for my account. At first I thought it might have been just my NSFW posts, but even my SFW and text posts don't embed anymore. I have not been able to replicate this issue with any other account's posts, even NSFW ones. Here's an example of a SFW text post of mine that won't embed: https://bskyx.app/profile/mobiusscarf.bsky.social/post/3l3vrwaqvn22j

**Comment by Delphox** [comment]
Yea it's affecting a bunch of accounts for me. Here's a couple examples:
https://bskyx.app/profile/gatorstooth.bsky.social/post/3l3j2uqejm72e
https://bskyx.app/profile/motsutambo.bsky.social/post/3k7trgfurp525
